### PR TITLE
Feature/event navigator

### PR DESCRIPTION
**Pull request by litchfld**
I've finished a stripped down version of the EventNavigator that replaces all the global input variables (g_data etc.)  

Since reworking the output in an extensible way is a complicated task in itself I've deferred that to the next iteration of this feature, so output is still done with globals, and the task of atomising the branch clean up is still to do (i.e ClearGlobalData bugs are unresolved and AnalysedPulseMap(Blah) still exist.  Beyond that the EventNavigator is not controlling ownership and access to branches either, it doesn't make much sense to do that without reworking the output format.  In my tests the output file has changed a little; file size is 32 bytes smaller in 1MiB (=1000 entries).  I haven't seen anything different browsing in an interactive session, so I'm assuming this is unimportant.

There are a few classes in here (such as the hash functions) that are aimed at future development. They should compile, but are not used at run time.  

Do people want time to play with this before I merge it back into develop?

### CODE REVIEW

**Comment by benkrikler** [comment]
I've not looked through the code, but it's great that this is ready in some form!  Do you have any idea how many things will break and how much work to rewrite it would be if you move this on to develop immediately?

**Comment by litchfld** [comment]
I _think_ nothing. AFAICR nothing I've change would manifest at run time, so as long as it compiles it should be OK. (Famous Last Words)

**Comment by benkrikler** [comment]
But surely at least the things that depend on TGlobalData will break since you're replacing this?  Isn't the point of this merge that we stop accessing that through a global pointer and stop looking at the banks it maps to directly?

**Comment by litchfld** [comment]
I think I already edited everything to use EventNavigator::Instance().GetRawData() instead.  There may be a few cases that have developed in the meantime. 

In any case, they shouldn't link because I removed the instantiation of the global pointer from main.  So fixing up build errors _should_ result in a correct run-time.

**Comment by litchfld** [comment]
> In any case, they shouldn't link because I removed the instantiation of the global pointer from main.

That is to say, more specifically it still exists as an extern declaration (at the least, because of the online code, where it is awkward to get rid of) but since it isn't defined anywhere any attempt to use it should cause the linker to barf.

**Comment by benkrikler** [comment]
In that case, I'm in favour of merging this in sooner rather than later.

**Pull request merged**
