### PR TITLE
Feature/bk update id classes

### PR DESCRIPTION
**Pull request by benkrikler**
I've finished putting through the various requests / changes for the ID classes:
- Case independent and hyphens -> underscores #101 
- Rewrite operator== and matches method #82
- default value for generator config #80  
- Change field separator to # #89 

I have also added `isFast()` and `isSlow()` methods to the Channel and source IDs.  This should be used to check if a channel is fast or slow instead of the previous `IDs::channel ch1("....."); ch1==IDs::Fast;`.  This old approach has been broken by the fact that operator== now returns true only if the enums contained in the channel ID are identical.  The new `matches` method takes over the role of the wildcarded matching that operator== had previously done.

Because of this change, I'm doing this as a pull request, although I have already put the correct changes into the parts of the code that needed updating.

### CODE REVIEW

**Comment by benkrikler** [comment]
If there are no objections I'm going to merge this by the end of today.

**Comment by AndrewEdmonds11** [comment]
I wouldn't object to you doing it sooner so I can rebase my feature branch and fix things while it's not on the develop branch

**Comment by benkrikler** [comment]
I've just done this.  The history might look a bit messy due to the rebasing.
I did `make clean; make all unit_test -j8` and everything looks ok on develop for me.

**Comment by AndrewEdmonds11** [comment]
@benkrikler, has this been pushed to github? I can't see it on the network graph...

**Comment by benkrikler** [comment]
Just pushed, sorry....

Sent from my mobileAndrewEdmonds11 notifications@github.com wrote:@benkrikler, has this been pushed to github? I can't see it on the network graph...

**Pull request closed without merging**
