### PR TITLE
Feature/bk si r2 pile up templates

### PR DESCRIPTION
**Pull request by benkrikler**
So to progress with the SiR2 pile-up I've returned to the template fitting.  I've put in a bunch of changes, predominantly tidying up code and some refactoring to make the code easier to understand.

This builds on work from issues:
- #7 (The original ticket discussing this)
- #129 (Previous discussion and example template pulses)
- #154 (Discusses finishing touches to the fitter)

I'll try and summarize the changes below.  Specific to Template fitting:
- Moved Template fitting code into a sub-directory at `src/TAP_generators/template_fitting`
- Added a TTemplate class.  I think John originally suggested this and it seems like a good idea.  Largely it wraps a TH1 to the template, but it allows us to store other values such as the number of pulses a template contains and the refine factor that was used.  This class also implements the addition of a pulse histogram to itself, although the relative offsets and scalings must be deduced elsewhere. 
- The `TemplateArchive` uses the new `TTemplate` class and has the option to store templates in the normal output file or a separate one.
- The `TemplateFitter` class uses the new `TTemplate` class.
- The `TemplateCreator` module has undergone a LOT of changes:
  -  The underlying algorithm is the basically the same.  The only change is to when we decide convergence of a template is reached.  It used to be done on the stability of the error on the max bin.  I've replaced to use the stability of the sum of all errors on all bins.
  -  Many changes to refactor of code or tidy up the aesthetics (code wrapping, indentation).
  -  I replaced the 4 or 5 maps that were in use with a single container of a struct which contains all the various fields we use to fit each channel.
  - I've added in the option to specify an integral ratio and integral range which selects pulses to add to the template. 
  - The cut that the PCF only sees 1 pulse on a TPI for it to be used in the template is now optional.
  - The module ends the run when all channels have template that are deemed as 'converged'.
  - New / tidied up modules file arguments

Some of the changes are a bit off-topic for this feature I'm afraid:
- SetupNavigator exceptions changed / added as discussed on issue #216 
- EventNavigator has a method to get the name of the output file

I was curious about a couple of things I saw:
1.  The final template is normalised so the integral is 1.  I thought we wanted the template's amplitude (max bin) to be scaled to 1.  Is there a particular reason why we normalize to the integral and not the max bin and can I change it?
2.  We check the max bin is less than 1/5th away from the edge of the waveform.  Would a fixed number of samples not make more sense?

I want to start using the templates this makes but I'll do that on a separate branch, so I'd like to merge this in as soon as I can.

### CODE REVIEW

**Comment by AndrewEdmonds11** [comment]
Thanks, Ben. That all looks good.

To answer your questions:

```
The final template is normalised so the integral is 1. I thought we wanted the template's amplitude (max bin) to be scaled to 1. Is there a particular reason why we normalize to the integral and not the max bin and can I change it?
```

I think, because we are generally going to be using this for fast pulses, we want to normalise the integral to one because that will give us the energy of the pulse.

```
We check the max bin is less than 1/5th away from the edge of the waveform. Would a fixed number of samples not make more sense?
```

The reason for this was because we don't want a truncated pulse being added to a fit and, since some pulses are much longer than others (particularly the Ge-S), I thought it best to be a fraction of the length

**Comment by benkrikler** [comment]
Ok,  that makes sense so I wont change these.  I'll wait a bit longer in case anyone else wants to comment but then I'll merge this all in.

**Comment by benkrikler** [comment]
And here are templates made from run2140 for no integral ratio cut and cuts corresponding to regions [a](http://www.hep.ph.ic.ac.uk/~bek07/alcap/sir2_pile_up#a), [b](http://www.hep.ph.ic.ac.uk/~bek07/alcap/sir2_pile_up#b) and [e](http://www.hep.ph.ic.ac.uk/~bek07/alcap/sir2_pile_up#e), as I described in the presentation on [elog:166](https://muon.npl.washington.edu/elog/mu2e/Analysis-R13/166).

No cut:
no_cut_template

Region a:
cut_a_template

Region b:
cut_b_template

Region e:
cut_e_template

**Comment by litchfld** [comment]
> > The final template is normalised so the integral is 1. I thought we wanted the template's amplitude (max bin) to be scaled to 1. Is there a particular reason why we normalize to the integral and not the max bin and can I change it?
> 
> I think, because we are generally going to be using this for fast pulses, we want to normalise the integral to one because that will give us the energy of the pulse.

So I think it does not technically matter.  Eventually our pulses must be calibrated to peaks of known energy from the sources.  Thus 
img
where _E_ are energy in MeV-like units, _S_ are template scaling factors and _A_ are the amplitude of pulses in ADC or any other unit.  [cal] is the calibration signal, and [0] is the template.  So It does not matter, as in practice we will use the ratio to the calibration pulses, and the template scale falls out automatically. The only important bits are making sure the  template errors are also scaled appropriately, and that the template is not at some extreme scale that introduces precision artefacts.

[^^ It's not necessarily  that simple: if we needed to stretch the pulses laterally then the question of what the relevant measure is important. But since that does not appear to be needed for any detector we can just use the amplitude scale.]

Because of the recovery undershoot I'd be tempted use an amplitude-based normalisation, since there's a small chance you get a near-cancellation between positive and negative bins in the integral, therefore losing some precision. But I doubt this loses more than on or two bits in practice, and it's unlikely to matter at all if integral of a `TH1F` is done at `double` precision.

**Comment by benkrikler** [comment]
The integral normalisation is also complicated a little bit by the refinement factor, though now that's stored alongside the template itself we've everything we'd need to incorporate that in any calculation of the integral.    

As you point out it makes little difference in the final calibrated value probably, so its more about the actual template itself.  I'm going to leave it as is I think just to save effort.

I think I'm going to merge this in now then and get working on the AP generator.

**Comment by benkrikler** [comment]
This is now merged.

**Comment by benkrikler** [comment]
I'm going to change to normalising to amplitude in the end since we only actually fit the template to amplitude and the integral doesn't actually appear in the fitting routine.

**Pull request closed without merging**
