### PR TITLE
Feature/unit test

### PR DESCRIPTION
**Pull request by litchfld**
Because coding up large chunks without being able to test them is painful and bug-prone, I added a test harness based on TUT: http://mrzechonek.github.io/tut-framework/

It shouldn't do anything to existing code, but adds a new directory `unit_test` to which, um, unit tests can be added.  So far there is only one test, an example, and I haven't yet checked that tests based on our code (as opposed to generic C++) will build.  The problem here is the Makefile: Because `main.o` is treated in the same way as any other object file I had to sneak around the back a bit to build the test executable.  If anyone enjoys playing with makefiles enough to want to clean that up and make sure it all works, then be my guest.  I'd personally rather leave it until I have no other choice. 

I also had to fake up instances of all the variables declared 'extern' which may come back to bite you if you try to test anything that relies on them behaving as they do in rootana's main.cpp. But it's better than nothing. 

Look at the file `src/unit_test/example_test.cpp` and try building and running the app with:

``` bash
bash$ cd rootana
bash$ make tut
bash$ ./unit_test
```

and let me know if what you think.

### CODE REVIEW

**Comment by litchfld** [comment]
Okay, I want to use this for code development on my event navigator branch.   I think I have two, maybe three choices:
1. (_Default_) finish/mergre the unit_test feature, then rebase event_navigator onto the HEAD of develop
2. Rebase event_navigator to the unit_test branch (does that work?)
3. Cherry-pick these commits and hop git works out when i come to merge back into develop.  

Anyone have any recommendations?  If it becomes a bottleneck i'll just go with my default.

**Comment by AndrewEdmonds11** [comment]
I would say option 1. By which I mean the first of your options labelled 1.

I think the second one may cause problems for us since it's not the way gitflow does things. I don't know how cherry pick works so can't make any judgment on that

**Comment by litchfld** [comment]
> I would say option 1. By which I mean the first of your options labelled 1.

Ops, didn't indent my markdown... [fixed now]

**Comment by benkrikler** [comment]
Are we ready to merge this?  I would like to use this to test the storage of  `IDs::source` within the rewritten TAnalysedPulse and also be able to test the various ID classes themselves.

**Comment by jrquirk** [comment]
After the next production run has been tagged I think we can merge this.

**Comment by litchfld** [comment]
How soon is that?  I wanted to start using this now, but if it's only a few hours to it'll probably be faster in the long run for me to go for a coffee rather than start doing some unfamiliar git operations. =S

**Comment by AndrewEdmonds11** [comment]
It should be OK to merge now. I've tagged the new release on master

**Comment by litchfld** [comment]
It is done. Now awaiting bug reports...

**Comment by benkrikler** [comment]
Just to point out Phill, that you should probably git rebase a branch before merging it.  You would have to do it locally on your system, but it means we can be much safer with handling conflicts in general and not breaking the develop branch.

**Comment by litchfld** [comment]
I thought git would refuse to merge if a rebase was is necessary?

**Comment by benkrikler** [comment]
It will only refuse if conflicts arise.  And a conflict is just a change on both branches in the same place, so it excludes a situation where someone has changed an interface or removed a global pointer for instance in some other part of your code that you didn't touch, but you do rely on.

In that case, no conflicts are actually found, git merges happily, whilst develop breaks painfully.  If you rebase your branch, check it works as expected and then finish (or close the pull request), you can be much more sure that it won't mess things up.

**Comment by litchfld** [comment]
Ah, a semantic conflict.  Sure; you'd do the same with CVS so my anachronistic habits would be largely correct. In this case though, I checked the history on github and was pretty sure there were no such issues... (famous last words)

**Comment by litchfld** [comment]
[i'll put this here untill such time as there is a stated need (or i get bored enough) for a wiki page]

BTW i noticed a feature in the way I set it up. Because all the tests will be run by the same executable, the test group in each case must be templated on  a different object i.e. in the line 

``` C++
typedef test_group<data> tg;
```

you must template off a different class (not `data`) or you will have a double definition/instantiation at link time.  The exact type you use is not important, so give it a name related to your test group.

**Pull request merged**
