### PR TITLE
Feature/bk tap tree

### PR DESCRIPTION
**Pull request by benkrikler**
[ I thought I'd opened this this morning, but it seems I opened the pull request to the old repository on Nam's account]

I've added two new modules to rootana which save and load TAPs to a tree.
These should be seen as temporary kludges so we can do this without the event navigator.

The work is done by transferring the TAPs stored in gAnalysedPulseMap into a set of TClonesArrays. I'm not sure therefore how this will handle specialised TAPs therefore, but when the use case arises we can always tweak things.

@litchfld , I made some tweaks to the event navigator itself so I would like your blessing to merge this in first.  The changes were:
- TGlobalData was being cleared directly in LoopSequence::Process and in `ClearGlobalData`.  I've taken it out ClearGlobalData now.  Im nervous this could cause new memory leaks, but I think in principle it's safe.
- The Preprocess, Process and Postprocess methods only checked the return codes of the module's methods after passing over each module.  I've changed it so it checks it for each module, which I think is the more natural behaviour.

The branches made from SavePulses can be used interactively so we can do simple analysis with TTree::Draw from now on.  More complex stuff can then load the pulses back into the framework with the LoadPulses module.

### CODE REVIEW

**Comment by benkrikler** [comment]
At the moment these modules are sitting in the src directory because I couldn't think where else to put them.  Should they go in some sort of `misc_modules` directory or something?

**Comment by litchfld** [comment]
> - TGlobalData was being cleared directly in LoopSequence::Process and in ClearGlobalData. I've taken it out ClearGlobalData now. Im nervous this could cause new memory leaks, but I think in principle it's safe.

Right now you probably have a better idea than me as I haven't looked at the code in over a week.  But naively that seems sensible. If it wasn't blowing up though I guess it must have been checking everything before deleting?

> -  The Preprocess, Process and Postprocess methods only checked the return codes of the module's methods after passing over each module. I've changed it so it checks it for each module, which I think is the more natural behaviour.

Not sure. I copied the behaviour from the old code. I think the rational is that all modules should have a chance to finish, so they all process the same number of events, and maybe even provide debugging info. That makes sense if the modules are all parallel (e.g. different versions of TPI => TAP, or plotting modules). It's less sensible if they are all sequential. And if it's a mix there's no right answer.

**Comment by benkrikler** [comment]
I think so far, most modules supposed to be used in serial.  The generators themselves are parallel but then that's down to Make**Pulses to control.  The plotting modules are quite parallel in nature I guess, but then missing one event off the bottom doesn't seem a big issue, whereas losing debugging info and error messages half-way up the output could be if it hides the fact there was a problem.

A related question is whether the Preprocess, Process and Postprocess methods should be run regardless of an error in the previous step.  My feeling is an error at Preprocess, we stop the run immediately, but an error in Process should still mean we execute Postprocess so that plots and outputs get saved and written to disk properly.  If we code cautiously when we implement AfterLastEntry then it should be safe to call that method still.

**Comment by litchfld** [comment]
Sounds reasonable. So schematically that would be...

``` C++
try {
  Preprocess()
  Process()
  PostProcess()
}
catch (preprocess_error) { PreProcessMessage(); }
catch (process_error) { 
  try { PostProcess() } 
  catch (...) { 
    //This block to ensure that the Process() error message is seen near the end 
    //of output even if PostProcess() produces a lot of output.
    ProcessMessage();
    throw;
   }  
   ProcessMessage();
}
catch (postprocess_error) {PostProcessMessage(); }

```

**Comment by benkrikler** [comment]
( I missed this from two comments back:)

> If it wasn't blowing up though I guess it must have been checking everything before deleting?

It blew up :p

> Sounds reasonable. So schematically that would be...
> 
> ```
> ....
> ```

Cool.  That looks good.  Should I put that in or do you want to do it?

**Comment by litchfld** [comment]
You better do it.  I'm not actually connected to my work machine right now.

**Comment by benkrikler** [comment]
This is merged now and so the Save and Load pulse modules are in place.  They only store TAPs, so a future extension is to also store TDPs.

**Pull request closed without merging**
