### PR TITLE
Feature/ae set tapalgorithm values in constructor

### PR DESCRIPTION
**Pull request by AndrewEdmonds11**
Ok, here's the pull request that covers issues #206 and #207. A few things I want to mention:
- There was a clash with having a constructor and an `operator()` so I renamed `operator()` to `Process()`
- At the moment, `SetupNavigator::GetCoarseTimeOffset()` takes an `IDs::source` but what I see in the code is that we give it `IDs::channel::str()`. If I understand correctly, this will set the generator and config of the source to `any`. So how does SetupNavigator know which row to get? (I will open a separate issue for discussion on this)
- It's annoying that we have to get the order of the parameter correct. Is there a clever (and easy) way around this? (I won't open another issue for this since I guess it's directly related to this pull request)
- Also, I wanted to set all the parameter values and create the algorithms in the generator's constructor rather than in the `ProcessPulses` method since (if I've understood correctly) there is one instance of a generator per channel. However, the generator's channel is not set by the time we get to the constructor. We saw this problem previously (this commit 68b6cad447b8e3d26d6bcdc9e24743d182b78e00 shows when we overloaded the SetChannel method to get the PCF in the FirstCompleteAPGenerator) but I'm wondering if it's simple and worth having it so that the generator's channel is set when it's constructed? (Again, I'll open a separate issue for this)

### CODE REVIEW

**Comment by benkrikler** [comment]
> There was a clash with having a constructor and an operator() so I renamed operator() to Process()

What do you mean by clash?  What code was causing it?  I've seen functors with arguments in the constructor and never seen this issue.  I don't mind changing the `operator()()` to `Process()` but this is distinctly breaking these away from the functor concept.  The concept is strong because it allows you to write generic code that takes either a functor or a function pointer a the compiler would find valid methods for each one.  In particular the STL makes use of this a lot, including in the `algorithms` functions.    I suspect in practice this won't impact us much, but it's not a trivial change you've put in there.

> `SetupNavigator::GetCoarseTimeOffset()` takes an IDs::source but what I see in the code is that we give it IDs::channel::str().

Is this implementing a check for what channel is being used? I've been thinking for a while now we need overloaded versions of `operator ==` and `matches` that except string arguments for all the ID classes.  Would that help here?

> It's annoying that we have to get the order of the parameter correct. Is there a clever (and easy) way around this? (I won't open another issue for this since I guess it's directly related to this pull request)

You could except a modules::options instance in the constructor and use since the Get methods would all throw exceptions if not set.  It feels like a brutal way to set values to avoid knowing the order of parameters in a constructor though.

**Comment by AndrewEdmonds11** [comment]
> What do you mean by clash?

I was getting a compilation error. Maybe it was related to something else:

```
Making object: 'obj/MaxBinAPGenerator.o'
src/TAP_generators/MaxBinAPGenerator.cpp: In member function ‘virtual int MaxBinAPGenerator::ProcessPulses(const PulseIslandList&, AnalysedPulseList&)’:
src/TAP_generators/MaxBinAPGenerator.cpp:48:34: error: ‘((MaxBinAPGenerator*)this)->MaxBinAPGenerator::fMaxBinTime’ cannot be used as a function
make: *** [obj/MaxBinAPGenerator.o] Error 1
```

and the code is:

``` C++
 // Set-up the algorithms
  fMaxBinAmplitude = new Algorithm::MaxBinAmplitude(pedestal, trigger_polarity);
  fMaxBinTime = new Algorithm::MaxBinTime(trigger_polarity, clock_tick_in_ns, time_shift);

  double amplitude, time;
  TAnalysedPulse* outPulse;

  for (PulseIslandList::const_iterator pulseIter = pulseList.begin(); pulseIter != pulseList.end(); pulseIter++) {
    amplitude = fMaxBinAmplitude->Process(*pulseIter);
    time = fMaxBinTime(*pulseIter); <--- this is the line being complained about

    // Make the TAnalysedPulse pulse
    outPulse=MakeNewTAP(pulseIter-pulseList.begin());
    outPulse->SetAmplitude(amplitude);
    outPulse->SetTime(time);
    //    outPulse->SetEnergy(energy); //AE (3rd Aug 2014): Commenting this out for the time being since we don't really know how we're doing calibration. The equation used before was:   energy = \
fECalibSlope * amplitude + fECalibOffset;
    // Add the pulse into the list
    analysedList.push_back(outPulse);

  }
```

I assumed it was because I have two uses for `()` but was confused why it couldn't tell the difference between the argument list.

> Is this implementing a check for what channel is being used?

There's no check being done in that function:

``` C++
double GetCoarseTimeOffset(const IDs::source& src) { return fCoarseTimeOffset.at(src); }
```

I'm not sure if it would be useful to have those functions or not

> It feels like a brutal way to set values to avoid knowing the order of parameters in a constructor though. 

I won't bother then. I guess if you're writing a generator you should at least be looking at the header of TAPAlgorithms anyway,

**Comment by benkrikler** [comment]
The error is because `fMaxBinTime` is a pointer to the functor.  You would need to write:

```
time = (*fMaxBinTime)(*pulseIter);
```

But do you need to `new` the algorithms anyway?  Then you don't need a pointer to the object and that line would be more readable.

**Comment by AndrewEdmonds11** [comment]
Well, at the time I had each algorithm as a member variable, and because I needed to create these with a proper constructor I just made the member variables pointers and used `new`.

I guess the algorithms don't need to be member variables and I can just instantiate it like so:

``` C++
MaxBinAPGenerator::ProcessPulses() {

   ...get the variables...

   Algorithm::MaxBinTime max_bin_time_alg(trigger_polarity, clock_tick_in_ns, time_shift);

   ...and then use it like so...

   max_bin_time_alg(*tpi);
}
```

Is this better?

**Comment by benkrikler** [comment]
They should be member variables so we have proper access to them and they get maintained between processing each pulses.  To access their constructors you use the generator's constructors initialisation list:

``` c++
MaxBinAPGenerator::MaxBinAPGenerator(modules::options* opts):
  fMaxBinTime( opts->GetDouble("trigger_polarity"), clock_tick_in_ns, time_shift), fMaxBinAmplitude(....)
{
 /// anything else
}
```

You get options out of the instance passed to the generator as normal, but beware that if this throws anything the destructor of the generator should be properly implemented to help tidy things up.

Of course, I don't think there's anything to stop you just doing:

``` c++
 fMaxBinTime = TAPAlgorithms::MaxBinTime( opts->GetDouble("trigger_polarity"), clock_tick_in_ns, time_shift);
```

provided the copy assignment `operator=(MaxBinTime&)` method is implemented, although the compiler will normally do this for you quite well with simple structs.

**Comment by AndrewEdmonds11** [comment]
Ok, I'm a bit confused now. With this option:

``` C++
MaxBinAPGenerator::MaxBinAPGenerator(modules::options* opts):
  fMaxBinTime( opts->GetDouble("trigger_polarity"), clock_tick_in_ns, time_shift), fMaxBinAmplitude(....)
{
 /// anything else
}
```

The generators aren't given the trigger polarity as an option, right? And the other things aren't known while it's a generator or have we decided to change this?

And then for this option:

``` C++
fMaxBinTime = TAPAlgorithms::MaxBinTime( opts->GetDouble("trigger_polarity"), clock_tick_in_ns, time_shift);
```

That line would just go in the place it currently is and I make the member variable a non-pointer again?

**Comment by benkrikler** [comment]
I'm sorry I'm trying to respond to these too hastily.  The constructor arguments in the first option are just examples.  You would need to obtain these values whichever way is appropriate.  I guess they're coming from the setup navigator so just use that. 

The second option is not so strong at protecting against meaningless parameter values, so I would prefer the first approach personally, and make all parameters and assignment operators private by default.

**Comment by AndrewEdmonds11** [comment]
Ok, so I now have the channels in the constructor and creating the algorithm in the initialiser list is fine. Except in CFTimeMBAmpAPGenerator, we have the following code:

``` C++
// In the constructor
fDontShiftTime = opts->GetBool("no_time_shift", false);
...
// When creating the algorithms
  double time_shift;
  if (fDontShiftTime)
    time_shift = 0;
  else
    time_shift = SetupNavigator::Instance()->GetCoarseTimeOffset(channel.str());
```

i.e. we decide on one of the parameter values based on a module option. I guess this can't go in the initialiser list so what's the best way to do this? Just pass the bool to the algorithm and then let it decide there? Would that work with the parameters being const now?

**Comment by AndrewEdmonds11** [comment]
Ok. So I think there are two ways to do this:

`1.` Create two algorithms in each generator. One with time_shift=0 and one with the correct time_shift and select on ProcessPulses which one we want:

``` C++
CFTimeAPGenerator::CFTimeAPGenerator(TAPGeneratorOptions* opts):
  TVAnalysedPulseGenerator("CFTimeAPGenerator",opts),
  // Set-up the algorithm in the generator list (it looks a bit messy)
  fConstantFractionTimeNoShift(SetupNavigator::Instance()->GetPedestal(GetChannel()),
                        TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        std::pow(2, TSetupData::Instance()->GetNBits(TSetupData::Instance()->GetBankName(GetChannel().str()))) - 1,
                        TSetupData::Instance()->GetClockTick(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        TSetupData::Instance()->GetTimeShift(0),
                        opts->GetDouble("constant_fraction", -0.10)),
  fConstantFractionTime(SetupNavigator::Instance()->GetPedestal(GetChannel()),
                        TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        std::pow(2, TSetupData::Instance()->GetNBits(TSetupData::Instance()->GetBankName(GetChannel().str()))) - 1,
                        TSetupData::Instance()->GetClockTick(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        TSetupData::Instance()->GetTimeShift(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        opts->GetDouble("constant_fraction", -0.10)) {

   fDontShiftTime = opts->GetBool("no_time_shift", false);
}

int CFTimeAPGenerator::ProcessPulses(const PulseIslandList& pulseList,
                                     AnalysedPulseList& analysedList) {

  for (unsigned int iTPI = 0; iTPI < pulseList.size(); ++iTPI) {
    TPulseIsland* tpi = pulseList.at(iTPI);

    double time;
    if (fDontShiftTime) {
       time = fConstantFractionTimeNoShift(tpi);
    }
    else {
       time = fConstantFractionTime(tpi);
    }

    TAnalysedPulse* tap = MakeNewTAP(iTPI);
    tap->SetTime(time);
    analysedList.push_back(tap);
  }

  return 0;
}
```

`2.` Get the actual value from the modules file (so if we don't want a time shift then we set it to 0):

``` C++
CFTimeAPGenerator::CFTimeAPGenerator(TAPGeneratorOptions* opts):
  TVAnalysedPulseGenerator("CFTimeAPGenerator",opts),
  // Set-up the algorithm in the generator list (it looks a bit messy)
  fConstantFractionTimeNoShift(SetupNavigator::Instance()->GetPedestal(GetChannel()),
                        TSetupData::Instance()->GetTriggerPolarity(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        std::pow(2, TSetupData::Instance()->GetNBits(TSetupData::Instance()->GetBankName(GetChannel().str()))) - 1,
                        TSetupData::Instance()->GetClockTick(TSetupData::Instance()->GetBankName(GetChannel().str())),
                        TSetupData::Instance()->GetTimeShift(opts->GetDouble("time_shift", TSetupData::Instance()->GetBankName(GetChannel().str())),
                        opts->GetDouble("constant_fraction", -0.10)) {

}
```

Problem with number 1 is that we would need to do this in all the generators and it double up on stuff. The problem with the second one is that it's different to the way we were doing it before and also means it's possible to set the time shift to whatever you want.

Since the second problem isn't a major one (it would just mean we have to remember to change the calibration config file and never use it for anything other than 0) and the first solution looks messy, I'm going to go with the second option.

**Comment by AndrewEdmonds11** [comment]
This should be ready for merging now. Does someone want to check it?

**Comment by jrquirk** [comment]
The time offset won't be available via the TSetupData I thought?

**Comment by AndrewEdmonds11** [comment]
That's right. I was just leaving that change to the release branch for no particular reason.

**Comment by litchfld** [comment]
These initialiser lines are huge.  You can save a lot of screen space with a few choice references, which, provided you can make them const, will also save you processor cycles (no repeated calls to Instance()) as well as making the code a bit more readable.

``` C++
/*const?*/ SetupNavigator& sn = SetupNavigator::Instance();
/*const?*/ SetupData& sd = SetupData::Instance();
fConstantFractionTime(sn->GetPedestal(GetChannel()),
                      sd->GetTriggerPolarity(sd->GetBankName(GetChannel().str())),
                      sd->GetClockTick(sd->GetBankName(GetChannel().str())),
                      opts->GetBool("no_time_shift") ? 0. : sn->GetCoarseTimeOffset(GetSource()),
                      opts->GetDouble("constant_fraction", -0.10)), 
                      //...
```

**But** you should also make use of the TSetupRecord, which encapsulates read access to TSetupData, (which is deprecated for offline - i.e. read - code)

``` C++
/*const?*/ SetupNavigator& sn = SetupNavigator::Instance();
const SetupRecord& sr = EventNavigator::Instance().GetSetupRecord();
fConstantFractionTime(sn->GetPedestal(GetChannel()),
                      sr->GetPolarity(GetChannel()),  sr->GetTickLength(GetChannel()),
                      opts->GetBool("no_time_shift") ? 0. : sn->GetCoarseTimeOffset(GetSource()),
                      opts->GetDouble("constant_fraction", -0.10)), 
                      //...
```

**Pull request closed without merging**
